SELECT  DISTINCT x.[ID_AGENTE], y.[ID AGENTE],
CASE
	WHEN x.[ID_AGENTE] = y.[ID AGENTE] THEN 'encontrou'
	WHEN x.[ID_AGENTE] <> y.[ID AGENTE] OR x.[ID_AGENTE] IS NULL THEN 'naotem'
	WHEN y.[ID AGENTE] IS NULL THEN  'naotem'
	END STATUS,
CASE
	WHEN x.[ID_AGENTE] = y.[ID AGENTE] OR y.[ID AGENTE]  IS NOT NULL THEN x.QTDE_VENDA
	ELSE 000
END CONTAGEM_X,
(SELECT COUNT(*) FROM [dbo].[teste_003] AS c WHERE c.[ID AGENTE] = x.ID_AGENTE GROUP BY c.[ID AGENTE]) AS CONT_Y

FROM [BIGDATA].[dbo].[teste_001] AS x
left join [dbo].[teste_003] as y
on y.[ID AGENTE] = x.ID_AGENTE
WHERE EXISTS (SELECT --*
				[ID AGENTE],
		CASE 
		WHEN RIGHT(LEFT(CAMPANHA,6),5) IN ('10048','10051') THEN 'AGV'
		WHEN RIGHT(LEFT(CAMPANHA,6),5) IN ('10002','10053') THEN 'PREDITIVO'
		ELSE CAMPANHA END AS CAMPANHA
		--SELECT *
		FROM [dbo].[teste_003]) AND y.[TIPO DE CHAMADA] = 'Discador'