WITH segmentacao_tim AS (

	SELECT DISTINCT 
		lagente.[ID AGENTE] AS IDAGENTE
		,CASE
		WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10048','10051') THEN 'AGV'
		WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10002','10053') THEN 'PREDITIVO'
		WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10052') THEN 'REPESCAGEM'
		ELSE lagente.CAMPANHA
		END AS TIPO_CAMPANHA
	
		,COUNT(DISTINCT csales.ID_VENDA) AS linhas
		,SUM(CASE WHEN lagente.[TIPO DE CHAMADA] LIKE '%DISCADOR%' THEN 1 ELSE 0 END) AS QTD_DERIV
		,SUM(CASE WHEN lagente.CLASSIFICACAO LIKE '%VENDA%' THEN 1 ELSE 0 END) AS QTD_VENDA
		,SUM(CASE WHEN lagente.[TIPO DE CHAMADA] LIKE '%Manual%' THEN 1 ELSE 0 END) AS QTDE_MANUAL
	FROM [TIM].[dbo].[LIGACOES_DOS_AGENTES_D_0] AS lagente
	LEFT JOIN [TIM].[dbo].[CUSTOM_SALES_D_0] AS csales ON csales.ID_TICKET = lagente.GRAVACAO
	WHERE  EXISTS(SELECT DISTINCT x.ID_AGENTE FROM TIM.dbo.PERFORMANCE_DOS_AGENTES_D_0 x WHERE x.ID_AGENTE = lagente.[ID AGENTE])
	GROUP BY lagente.[ID AGENTE],lagente.CAMPANHA

)

SELECT a.IDAGENTE
,a.QTD_DERIV
,a.QTD_VENDA
,a.QTDE_MANUAL
,a.TIPO_CAMPANHA
,CASE
	WHEN ROUND(SUM(NULLIF(CONVERT(FLOAT,QTD_VENDA),0)/NULLIF(CONVERT(FLOAT,QTD_DERIV),0)),2) IS NULL THEN 0
	ELSE ROUND(SUM(NULLIF(CONVERT(FLOAT,QTD_VENDA),0)/NULLIF(CONVERT(FLOAT,QTD_DERIV),0)),2)
END CONV_DERIVADA

FROM segmentacao_tim as a


GROUP BY IDAGENTE,QTD_DERIV,QTD_VENDA,QTDE_MANUAL,TIPO_CAMPANHA
