WITH tempo_operacional_segmentacao_tim AS (
	SELECT  
		pagente.ID_AGENTE
		,pagente.TEMPO_LOGADO
		,pagente.TEMPO_DISPONIVEL
		,pagente.TEMPO_MEDIO_DISPONIVEL
		,pagente.TEMPO_FALADO
		,ROUND(pagente.TEMPO_LOGADO / 3600.0,2) AS HORAS_LOGADO
		,ROUND(pagente.TEMPO_FALADO / 3600.0,2) AS HORAS_FALANDO
		,ROUND(pagente.TEMPO_FALADO / CONVERT(FLOAT,TEMPO_LOGADO),2) AS PORCENTAGEM_TEMPO_FALADO
		,ROW_NUMBER() OVER(PARTITION BY pagente.TEMPO_LOGADO ORDER BY pagente.ID_CAMPANHA DESC) AS DuplicateCount
		,pagente.DATA AS DATACADASTRO
		,pagente.ID_CAMPANHA
		,ROUND(SUM(CASE WHEN tp.TIPIFICACAO_2 = 'Venda' THEN 1 ELSE 0 END) / NULLIF(CONVERT(FLOAT,COUNT(DISTINCT lagente.GRAVACAO)),0) * 100,2) AS CONVERTIDAS
		FROM TIM.dbo.PERFORMANCE_DOS_AGENTES_D_0 AS pagente
		LEFT JOIN [TIM].[dbo].[LIGACOES_DOS_AGENTES_D_0] AS lagente ON lagente.[ID AGENTE] = pagente.ID_AGENTE
		LEFT JOIN TIM.dbo.TIPIFICACAO AS tp ON tp.AGENTCLASS = lagente.CLASSIFICACAO
		GROUP BY pagente.ID_AGENTE
		,pagente.TEMPO_LOGADO
		,pagente.TEMPO_DISPONIVEL
		,pagente.TEMPO_FALADO
		,pagente.DATA
		,pagente.ID_CAMPANHA
		,pagente.TEMPO_MEDIO_DISPONIVEL
		),
		calcula_porcentagem AS (
		SELECT ID_AGENTE
			,TEMPO_LOGADO
			,TEMPO_DISPONIVEL
			,TEMPO_MEDIO_DISPONIVEL
			,TEMPO_FALADO,HORAS_LOGADO
			,HORAS_FALANDO
			,PORCENTAGEM_TEMPO_FALADO
			,DATACADASTRO
			,ID_CAMPANHA
			,RANK() OVER(ORDER BY  CONVERTIDAS ASC) AS RANKING
			,NTILE(3) OVER(ORDER BY CONVERTIDAS DESC) AS grupos

			,CASE
				WHEN CONVERTIDAS IS NULL THEN 0
				ELSE CONVERTIDAS
				END CONVERTIDAS
		 ,ROUND((select CONVERT(FLOAT,SUM(CONVERTIDAS)/COUNT(*)) * 100 from tempo_operacional_segmentacao_tim),2) media_valor
	
		FROM tempo_operacional_segmentacao_tim
		WHERE DuplicateCount = 1
		GROUP BY ID_AGENTE
			,TEMPO_LOGADO
			,TEMPO_DISPONIVEL
			,TEMPO_MEDIO_DISPONIVEL
			,TEMPO_FALADO
			,HORAS_LOGADO
			,HORAS_FALANDO
			,PORCENTAGEM_TEMPO_FALADO
			,DATACADASTRO
			,ID_CAMPANHA
			,CONVERTIDAS
	
)

SELECT DISTINCT 
ID_AGENTE
,TEMPO_LOGADO
,TEMPO_DISPONIVEL
,TEMPO_MEDIO_DISPONIVEL
,TEMPO_FALADO
,HORAS_LOGADO
,HORAS_FALANDO
,PORCENTAGEM_TEMPO_FALADO
,DATACADASTRO
,CONVERTIDAS
,CASE
	WHEN CONVERT(FLOAT,[HORAS_LOGADO]) < 2.0  THEN	'Menos de +2 Horas'
	WHEN CONVERT(FLOAT,[HORAS_LOGADO]) >= 2 AND (CONVERT(FLOAT,CONVERTIDAS*100)) >= 4.0 THEN 'Conversão + 4%'
	WHEN CONVERT(FLOAT,[HORAS_LOGADO]) >= 2 AND (CONVERT(FLOAT,CONVERTIDAS*100)) <  AVG(CONVERT(FLOAT,media_valor)) * 0.5  THEN 'Desempenho Baixo'
	WHEN CONVERT(FLOAT,[HORAS_LOGADO]) >= 2 AND (CONVERT(FLOAT,CONVERTIDAS*100)) >= AVG(CONVERT(FLOAT,media_valor)) * 0.5  THEN 'Desempenho Mediano'

	END status_segmentacao

FROM calcula_porcentagem
GROUP BY ID_AGENTE
,TEMPO_LOGADO
,TEMPO_DISPONIVEL
,TEMPO_MEDIO_DISPONIVEL
,TEMPO_FALADO
,HORAS_LOGADO
,HORAS_FALANDO
,PORCENTAGEM_TEMPO_FALADO
,DATACADASTRO
,CONVERTIDAS
			  

-- Teste CHECANDO TABELA TEMPORARIA

IF OBJECT_ID('#resultado_segmentacao_derivado') IS NOT NULL 
BEGIN
	DROP TABLE #resultado_segmentacao_derivado

	CREATE TABLE #resultado_segmentacao_derivado(
		idagente INT,
		qtde_derivada INT,
		qtde_venda INT,
		qtde_manual INT,
		conve_derivada FLOAT

	)
END
ELSE
	BEGIN
		PRINT 'INSERT'
	END


WITH segmentacao_tim AS (

	SELECT DISTINCT 
		lagente.[ID AGENTE] AS IDAGENTE
		,CASE
		WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10048','10051') THEN 'AGV'
		WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10002','10053') THEN 'PREDITIVO'
		WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10052') THEN 'REPESCAGEM'
		ELSE lagente.CAMPANHA
		END AS TIPO_CAMPANHA
	
		,COUNT(DISTINCT csales.ID_VENDA) AS linhas
		,SUM(CASE WHEN lagente.[TIPO DE CHAMADA] LIKE '%DISCADOR%' THEN 1 ELSE 0 END) AS QTD_DERIV
		,SUM(CASE WHEN lagente.CLASSIFICACAO LIKE '%VENDA%' THEN 1 ELSE 0 END) AS QTD_VENDA
		,SUM(CASE WHEN lagente.[TIPO DE CHAMADA] LIKE '%Manual%' THEN 1 ELSE 0 END) AS QTDE_MANUAL
	FROM [TIM].[dbo].[LIGACOES_DOS_AGENTES_D_0] AS lagente
	LEFT JOIN [TIM].[dbo].[CUSTOM_SALES_D_0] AS csales ON csales.ID_TICKET = lagente.GRAVACAO
	GROUP BY lagente.[ID AGENTE],lagente.CAMPANHA

)

SELECT IDAGENTE
,QTD_DERIV
,QTD_VENDA
,QTDE_MANUAL
,TIPO_CAMPANHA
,CASE
	WHEN ROUND(SUM(NULLIF(CONVERT(FLOAT,QTD_VENDA),0)/NULLIF(CONVERT(FLOAT,QTD_DERIV),0)),2) IS NULL THEN 0
	ELSE ROUND(SUM(NULLIF(CONVERT(FLOAT,QTD_VENDA),0)/NULLIF(CONVERT(FLOAT,QTD_DERIV),0)),2)
END CONV_DERIVADA

FROM segmentacao_tim
GROUP BY IDAGENTE,QTD_DERIV,QTD_VENDA,QTDE_MANUAL,TIPO_CAMPANHA
