
WITH tab_venda AS (
		SELECT NOME_CLIENTE
		,ROW_NUMBER() OVER (ORDER BY newId())  AS IDCLIENTE
		,ROW_NUMBER() OVER (ORDER BY ESTADO)  AS ESTADO
		,ROW_NUMBER() OVER (ORDER BY CIDADE)  AS CIDADE

		FROM BIGDATA.dbo.tabela_005
		GROUP BY NOME_CLIENTE 
)


select * from tab_venda

  SELECT DISTINCT SEXO,ID_AGENTE,ID_VENDA,ID_TICKET
  ,CIDADE
  ,ESTADO
  ,TIPO_PLANO
  ,OPERADORA
  ,NOME_CLIENTE
  , CASE
	WHEN SEXO = 'Feminino' THEN 1
	ELSE 0
	END BITSEXO
,CASE
	WHEN OPERADORA = 'OI' THEN 1
	WHEN OPERADORA = 'CLARO' THEN 2
	WHEN OPERADORA = 'CONTA ONLINE' THEN 3
	WHEN OPERADORA = 'VIVO' THEN 4
	WHEN OPERADORA = 'CTBC' THEN 5
	WHEN OPERADORA = 'SERCOMTEL' THEN 6
	WHEN OPERADORA = 'DETALHADA' THEN 7
	ELSE 'NAOTEM'
	END BITOPERADORA

 FROM BIGDATA.dbo.tabela_005

  WHERE CIDADE IS NOT NULL AND ESTADO IS NOT NULL AND OPERADORA IS NOT NULL AND NOME_CLIENTE IS NOT NULL