WITH tempo_operacional_segmentacao_tim AS (
	SELECT  
		pagente.ID_AGENTE
		,pagente.TEMPO_LOGADO
		,pagente.TEMPO_DISPONIVEL
		,pagente.TEMPO_MEDIO_DISPONIVEL
		,SUM(CONVERT(FLOAT,pagente.TEMPO_FALADO)) AS TEMPO_FALADO
		,lagente.GRAVACAO
		,pagente.CAMPANHA

		,ROUND(pagente.TEMPO_LOGADO / 3600.0,2) AS HORAS_LOGADO
		,ROUND(pagente.TEMPO_FALADO / 3600.0,2) AS HORAS_FALANDO
		,ROUND(pagente.TEMPO_FALADO / CONVERT(FLOAT,TEMPO_LOGADO),2) AS PORCENTAGEM_TEMPO_FALADO
		,ROW_NUMBER() OVER(PARTITION BY pagente.TEMPO_LOGADO ORDER BY pagente.ID_CAMPANHA DESC,pagente.TEMPO_DISPONIVEL,pagente.TEMPO_DISPONIVEL DESC,pagente.ID_AGENTE DESC) AS DuplicateCount
		,pagente.DATA AS DATACADASTRO
		,pagente.ID_CAMPANHA
		,ROUND(SUM(CASE WHEN tp.TIPIFICACAO_2 = 'Venda' THEN 1 ELSE 0 END) / NULLIF(CONVERT(FLOAT,COUNT(DISTINCT lagente.GRAVACAO)),0) * 100,2) AS CONVERTIDAS
		--,RANK() OVER(ORDER BY  ROUND(SUM(CASE WHEN tp.TIPIFICACAO_2 = 'Venda' THEN 1 ELSE 0 END) / NULLIF(CONVERT(FLOAT,COUNT(DISTINCT lagente.GRAVACAO)),0) * 100,2) DESC,ROUND(pagente.TEMPO_LOGADO / 3600.0,2) DESC) RANKING
		,CASE
			WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10048','10051') THEN 'AGV'
			WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10002','10053') THEN 'PREDITIVO'
			WHEN RIGHT(LEFT(lagente.CAMPANHA,6),5) IN ('10052') THEN 'REPESCAGEM'
			ELSE lagente.CAMPANHA
		END AS TIPO_CAMPANHA,

		COUNT(DISTINCT csales.ID_VENDA) AS linhas
		,SUM(CASE WHEN lagente.[TIPO DE CHAMADA] LIKE '%DISCADOR%' THEN 1 ELSE 0 END) AS QTD_DERIV
		,SUM(CASE WHEN lagente.CLASSIFICACAO LIKE '%VENDA%' THEN 1 ELSE 0 END) AS QTD_VENDA
		,SUM(CASE WHEN lagente.[TIPO DE CHAMADA] LIKE '%Manual%' THEN 1 ELSE 0 END) AS QTDE_MANUAL
		FROM TIM.dbo.PERFORMANCE_DOS_AGENTES_D_0 AS pagente
		LEFT JOIN [TIM].[dbo].[LIGACOES_DOS_AGENTES_D_0] AS lagente ON lagente.[ID AGENTE] = pagente.ID_AGENTE
		LEFT JOIN TIM.dbo.TIPIFICACAO AS tp ON tp.AGENTCLASS = lagente.CLASSIFICACAO
		LEFT JOIN [TIM].[dbo].[CUSTOM_SALES_D_0] AS csales ON csales.ID_TICKET = lagente.GRAVACAO

		WHERE  EXISTS(SELECT DISTINCT x.ID_AGENTE FROM TIM.dbo.PERFORMANCE_DOS_AGENTES_D_0 x WHERE x.ID_AGENTE = lagente.[ID AGENTE])
		GROUP BY 
		pagente.ID_AGENTE
		,pagente.TEMPO_LOGADO
		,pagente.TEMPO_DISPONIVEL
		,pagente.TEMPO_FALADO
		,pagente.DATA
		,pagente.ID_CAMPANHA
		,pagente.TEMPO_MEDIO_DISPONIVEL
		,lagente.GRAVACAO
		,pagente.CAMPANHA
	   ,lagente.[ID AGENTE]
	   ,lagente.CAMPANHA
	 
		
)
		




SELECT i.ID_CAMPANHA
, i.ID_AGENTE
,SUM(CONVERT(FLOAT,i.HORAS_LOGADO)) AS HORAS_LOGADO
,SUM(CONVERT(FLOAT,i.HORAS_FALANDO)) AS HORAS_FALANDO
,SUM(CONVERT(FLOAT,i.TEMPO_FALADO)) AS TEMPO_FALADO
,SUM(CONVERT(FLOAT,i.QTD_DERIV)) AS QTD_DERIV
,SUM(CONVERT(FLOAT,i.QTD_VENDA)) AS QTD_VENDA
,SUM(CONVERT(FLOAT,i.CONVERTIDAS)) AS CONVERTIDAS
,i.DATACADASTRO
,i.TIPO_CAMPANHA
,(SELECT DISTINCT COUNT(x.GRAVACAO) FROM tempo_operacional_segmentacao_tim x WHERE x.ID_AGENTE = i.ID_AGENTE GROUP BY x.ID_AGENTE ) AS CONTAGEM_LIGACOES


FROM tempo_operacional_segmentacao_tim AS i
WHERE DuplicateCount =1 
GROUP BY 
i.ID_CAMPANHA
, i.ID_AGENTE
,i.DATACADASTRO
,i.TIPO_CAMPANHA
,i.QTD_DERIV