

WITH tab_venda AS (
		SELECT DISTINCT NOME_CLIENTE, ID_TICKET,ESTADO,CIDADE 
		,ROW_NUMBER() OVER (ORDER BY newId())  AS IDCLIENTE
		,ROW_NUMBER() OVER (ORDER BY ESTADO)  AS IDESTADO
		,ROW_NUMBER() OVER (ORDER BY CIDADE)  AS IDCIDADE

		FROM BIGDATA.dbo.tabela_005
		GROUP BY ESTADO, CIDADE,NOME_CLIENTE,ID_TICKET

)

SELECT DISTINCT 
C.ID_VENDA
,A.ID_TICKET
,A.IDCLIENTE
,A.NOME_CLIENTE
,A.ESTADO
,A.IDCIDADE
,A.IDESTADO
,(SELECT DISTINCT COUNT(*) AS CONTCLIENTE
FROM tab_venda AS T WHERE T.NOME_CLIENTE = C.NOME_CLIENTE GROUP BY T.NOME_CLIENTE) AS QUANTIDADECLIENTE
,(SELECT DISTINCT COUNT(*) AS CONTCLIENTE
FROM tab_venda AS T WHERE T.ESTADO = C.ESTADO GROUP BY T.ESTADO) AS QUANTIDADEESTADO
,(SELECT DISTINCT COUNT(*) AS CONTCLIENTE
FROM tab_venda AS T WHERE T.CIDADE = C.CIDADE GROUP BY T.CIDADE) AS QUANTIDADE_CIDADE

FROM BIGDATA.dbo.tabela_005 AS C
LEFT JOIN tab_venda AS A ON A.ID_TICKET = C.ID_TICKET
WHERE C.ID_VENDA IS NOT NULL AND C.ID_TICKET IS NOT NULL
