WITH IDTABELA AS (
		SELECT PLANO,
		ROW_NUMBER() OVER (ORDER BY newId())  AS IDPRODUTO
		FROM  BIGDATA.dbo.teste_als_segmentacao
		GROUP BY PLANO 
)

SELECT
DISTINCT
I.PLANO
,I.ID_TICKET
,I.ID_VENDA
,X.IDPRODUTO
,(SELECT DISTINCT COUNT(c.PLANO) AS CONT FROM IDTABELA c  
WHERE c.PLANO = X.PLANO
GROUP BY c.IDPRODUTO,c.PLANO) CONTAGEM

,I.DATA

,REPLACE(A.[%_CONVERSAO_VENDA], ',', '.') AS CONVERSAO_VENDA
,REPLACE(A.HORAS_LOGADO, ',', '.') AS HORAS_LOGADO
,REPLACE(A.HORAS_FALANDO, ',', '.') AS HORAS_FALANDO
,A.HORAS_LOGADO
,A.QTDE_LIGACOES
,A.QTDE_LINHA
,A.QTDE_VENDA
,A.RANKING
,A.Quartile
,COUNT(I.ID_TICKET) AS TOTVENDA
FROM BIGDATA.dbo.teste_als_segmentacao AS I
LEFT JOIN IDTABELA AS X ON I.PLANO = X.PLANO
LEFT JOIN [BIGDATA].[dbo].[relatorio_tabela] AS A ON A.ID_AGENTE = I.ID_AGENTE AND I.ID_AGENTE = A.ID_AGENTE
LEFT JOIN [BIGDATA].[dbo].[tabela_005] AS Y ON Y.ID_TICKET = I.ID_TICKET AND X.PLANO = Y.PLANO
WHERE A.[%_CONVERSAO_VENDA] IS NOT NULL
GROUP BY 

I.DATA
,A.[%_CONVERSAO_VENDA]
,A.HORAS_LOGADO
,A.HORAS_FALANDO
,A.HORAS_LOGADO
,A.QTDE_LIGACOES
,A.QTDE_LINHA
,A.QTDE_VENDA
,I.PLANO
,I.ID_TICKET
,I.ID_VENDA
,X.IDPRODUTO
,X.PLANO
,A.RANKING
,A.Quartile
